### ISSUE TITLE
針對一些半形的 ( 與 ) 括號是否應該在前後加上空白字元

### ISSUE THREAD

**Issue by doggy8088** [Talljack/vscode-auto-space#15]
這是一個可以討論的議題，不知道作者怎麼想？

舉例：

```
不能信任那些Terminal(終端機)或Editor(編輯器)用白底的人
```

選項1: (目前此 extension 會這樣加空白)

```
不能信任那些 Terminal(終端機)或 Editor(編輯器)用白底的人
```

選項2: (我比較推薦的結果)

```
不能信任那些 Terminal (終端機) 或 Editor (編輯器) 用白底的人
```

> 我推薦使用 [pangu.js](https://github.com/vinta/pangu.js) 來進行轉換，此 package 發展多年，蠻穩定的。

**Comment by Talljack** [comment]
我认为下面这种结果也是我希望的，后续会修改一下

**Comment by Talljack** [comment]
fixed #20
