### ISSUE TITLE
vscode.workspace.onWillSaveTextDocument might change to DocumentFormattingEditProvider

### ISSUE THREAD

**Issue by doggy8088** [Talljack/vscode-auto-space#17]
https://github.com/Talljack/vscode-auto-space/blob/17c6cd287ba1529b8c834461d081dc67ad573a29/src/index.ts#L34-L40

FYI: https://github.com/microsoft/vscode/issues/145859#issuecomment-1076162885

**Comment by Talljack** [comment]
fixed in #252
