### ISSUE TITLE
unexpected auto-spacing issue

### ISSUE THREAD

**Issue by oopooa** [Talljack/vscode-auto-space#214]
There are a few situations where I don't want spaces in my text, but when I delete them, they reappear as soon as I save the file.

Here are some situations where I have issues with spaces being automatically added in my test.md file.

case 1:
target = 18, int [] nums = [1, 5, 7, 11], 循环三次的 map 结果是 {1 = 0, 5 = 1, 7 = 2}

case 2:
```java
    if (index < 0 || index > size) {
        throw new IllegalArgumentException ("非法下标参数");
    }
```

in case one, I don't want a space between int and [] because int[] should be treated as a single entity.
in case two, a space is always inserted between IllegalArgumentException and ("非法下标参数"), which is incorrect Java syntax.

How can I resolve these unexpected behaviors

**Comment by Talljack** [comment]
I'll check it or offer some config to user
