### ISSUE TITLE
Error: Cannot find module 'pangu'

### ISSUE THREAD

**Issue by Lord-Turmoil** [Talljack/vscode-auto-space#22]
When I tried to execute 'Auto Add Space' command, it prompted this error.

![image](https://github.com/Talljack/vscode-auto-space/assets/68287135/e92fa106-357d-4fb2-8695-5930ad433625)

I searched for it in the logging, and found these messages.

```
2023-11-13 17:00:31.104 [error] Activating extension talljack.vscode-auto-space failed due to an error:
2023-11-13 17:00:31.104 [error] Error: Cannot find module 'pangu'
Require stack:
- c:\Users\xxxx\.vscode\extensions\talljack.vscode-auto-space-1.3.4\dist\index.js
- e:\IDE\Microsoft VS Code\resources\app\out\vs\loader.js
- e:\IDE\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- e:\IDE\Microsoft VS Code\resources\app\out\bootstrap-fork.js
-
...
```

It seems that module `pangu` is missing on my computer. So are there any way to solve this?

**Comment by Talljack** [comment]
fixed it by use [excluding-all-packages](https://tsup.egoist.dev/#excluding-all-packages), please update it `1.3.5` version
