### ISSUE TITLE
Feature Request: Exclude Files with Specific Extensions

### ISSUE THREAD

**Issue by monup165** [Talljack/vscode-auto-space#319]
I would like to request a feature that allows for the exclusion of files with specific extensions, such as .txt.  Here's the background and justification for this feature:

I have a file named test.txt which has been collaboratively edited over the years.  I am interested in preserving the original content structure of this file and do not wish to make any changes to it.  The ability to exclude certain file types would be beneficial in maintaining the integrity of specific documents while allowing updates to other files.

can you add this feature?

**Comment by Talljack** [comment]
Yes, I think that's reasonable. I'll do it. Thanks

**Comment by Talljack** [comment]
fixed in #329
